/* Vercel용 캐치올 함수(api/[...slug].js)와 사내망 독립 실행형 서버
   (standalone.js)가 함께 쓰는 라우트 테이블. require()를 각각
   정적 문자열로 써서 Vercel 번들러가 모든 라우트 파일을 빠짐없이
   포함시키도록 하고, 화이트리스트에 없는 이름은 애초에 불러올 수
   없게 막는다. */
const routes = {
  "accounts": () => require("../accounts.js"),
  "admin-notifications": () => require("../admin-notifications.js"),
  "agent": () => require("../agent.js"),
  "approve-account": () => require("../approve-account.js"),
  "approve-dash-request": () => require("../approve-dash-request.js"),
  "attach": () => require("../attach.js"),
  "comment": () => require("../comment.js"),
  "comment-delete": () => require("../comment-delete.js"),
  "dash-access": () => require("../dash-access.js"),
  "dash-rank": () => require("../dash-rank.js"),
  "dash-request": () => require("../dash-request.js"),
  "dash-request-cancel": () => require("../dash-request-cancel.js"),
  "dash-requests": () => require("../dash-requests.js"),
  "dash-stats": () => require("../dash-stats.js"),
  "dashboards-data": () => require("../dashboards-data.js"),
  "favorites": () => require("../favorites.js"),
  "health": () => require("../health.js"),
  "health-waive": () => require("../health-waive.js"),
  "history": () => require("../history.js"),
  "html-backup": () => require("../html-backup.js"),
  "html-history": () => require("../html-history.js"),
  "login": () => require("../login.js"),
  "logout": () => require("../logout.js"),
  "lounge-attach": () => require("../lounge-attach.js"),
  "lounge-delete": () => require("../lounge-delete.js"),
  "lounge-edit": () => require("../lounge-edit.js"),
  "lounge-like": () => require("../lounge-like.js"),
  "lounge-list": () => require("../lounge-list.js"),
  "lounge-post": () => require("../lounge-post.js"),
  "lounge-reply": () => require("../lounge-reply.js"),
  "lounge-reply-delete": () => require("../lounge-reply-delete.js"),
  "lounge-reply-edit": () => require("../lounge-reply-edit.js"),
  "manual": () => require("../manual.js"),
  "manual-delete": () => require("../manual-delete.js"),
  "manual-save": () => require("../manual-save.js"),
  "manuals": () => require("../manuals.js"),
  "me": () => require("../me.js"),
  "notice": () => require("../notice.js"),
  "pending-accounts": () => require("../pending-accounts.js"),
  "popular": () => require("../popular.js"),
  "popup": () => require("../popup.js"),
  "popup-admin": () => require("../popup-admin.js"),
  "popup-delete": () => require("../popup-delete.js"),
  "popup-dismiss": () => require("../popup-dismiss.js"),
  "popup-image": () => require("../popup-image.js"),
  "popup-save": () => require("../popup-save.js"),
  "post": () => require("../post.js"),
  "post-delete": () => require("../post-delete.js"),
  "post-edit": () => require("../post-edit.js"),
  "post-like": () => require("../post-like.js"),
  "posts": () => require("../posts.js"),
  "register": () => require("../register.js"),
  "render": () => require("../render.js"),
  "req-file": () => require("../req-file.js"),
  "request-status": () => require("../request-status.js"),
  "save": () => require("../save.js"),
  "share-add": () => require("../share-add.js"),
  "share-delete": () => require("../share-delete.js"),
  "share-edit": () => require("../share-edit.js"),
  "share-file": () => require("../share-file.js"),
  "share-list": () => require("../share-list.js"),
  "site-stats": () => require("../site-stats.js"),
  "site-visit": () => require("../site-visit.js"),
  "systems": () => require("../systems.js"),
  "upload-html": () => require("../upload-html.js"),
};

function resolveHandler(name) {
  const loader = name ? routes[name] : null;
  return loader ? loader() : null;
}

module.exports = { routes, resolveHandler };
